# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # NPM 1
  - package-ecosystem: "npm" # 
    directory: "/https_listener_stub/" # Location of package manifests
    schedule:
      interval: "weekly"

    # NPM 2
  - package-ecosystem: "npm" 
    directory: "/process-file-via-cmdline-args/" # Location of package manifests
    schedule:
      interval: "weekly"
